development:
  password: 50add912012ac2ffa59df7cb3bdc9083
  theme_id: "43779522627"
  store: living-streets.myshopify.com
  ignore_files:
  - .gitignore
  - README.md
  - config/settings_data.json
  

