development:
  password: 62337ebbb8ac30bc53abf9f1dc4186a2
  theme_id: "36117676096"
  store: mightymango-development.myshopify.com
  ignore_files:
  - .gitignore
  - README.md
  - config/settings_data.json
  

